### ISSUE TITLE
Determine validation rules per resume type

### ISSUE THREAD

**Issue by qmcree** [qmcree/resume-builder#19]
For example:

- How may tasks can be added per job? 
- ...

**Comment by emilyplunkett** [comment]
[RESUME RULE SHEET.docx](https://github.com/qmcree/resume-builder/files/1049952/RESUME.RULE.SHEET.docx)

**Comment by emilyplunkett** [comment]
I'll post templates for each type of resume as well :)

**Comment by emilyplunkett** [comment]
[COMBINATION.docx](https://github.com/qmcree/resume-builder/files/1049953/COMBINATION.docx)

**Comment by emilyplunkett** [comment]
[CHRONLOGICAL.docx](https://github.com/qmcree/resume-builder/files/1049954/CHRONLOGICAL.docx)

**Comment by emilyplunkett** [comment]
[TARGETED.docx](https://github.com/qmcree/resume-builder/files/1049955/TARGETED.docx)

**Comment by emilyplunkett** [comment]
[FUNCTIONAL.docx](https://github.com/qmcree/resume-builder/files/1049958/FUNCTIONAL.docx)
