### ISSUE TITLE
Add Content Information 

### ISSUE THREAD

**Issue by emilyplunkett** [qmcree/resume-builder#24]
[COMBINATION HELP TEXT.docx](https://github.com/qmcree/resume-builder/files/1050533/COMBINATION.HELP.TEXT.docx)
[LANDING CLOSING PAGE-Content.docx](https://github.com/qmcree/resume-builder/files/1050532/LANDING.CLOSING.PAGE-Content.docx)

**Comment by ChristianArredondo** [comment]
![screen shot 2017-06-04 at 12 50 25 pm](https://cloud.githubusercontent.com/assets/24460948/26764027/82858c42-4924-11e7-8991-affeb1ffc9f3.png)

![screen shot 2017-06-04 at 1 06 42 pm](https://cloud.githubusercontent.com/assets/24460948/26764141/b5d5aed6-4926-11e7-82f8-016626dfeffe.png)
